name: Using reusable

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: My job

    steps:
      - uses: actions/checkout@v4
      - id: my_id
        uses: LangBledsoe/2.2-Actions@main
        with:
          input_string: 'This is not the default string'
